# Spring Boot configuration
spring:
  profiles:
    active: development
# Database
  data:
    mongodb:
      uri: mongodb://acua-dev:7gEg8kzt6jKllxi4Nio34lRRnwLqWFGgHk5fQXHlKxhsQJ9axJPEClYuE5AzTlzLgxmulpYmfV7Ul1524NPcNg==@acua-dev.documents.azure.com:10255/acua-dev?ssl=true&replicaSet=globaldb
#      host: acua-dev.documents.azure.com
#      port: 10255
#      database: acua-dev
#      username: acua-dev
#      password: 7gEg8kzt6jKllxi4Nio34lRRnwLqWFGgHk5fQXHlKxhsQJ9axJPEClYuE5AzTlzLgxmulpYmfV7Ul1524NPcNg==

# Logging
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    com.hello: DEBUG
    org.springframework: INFO
    org.mongodb: DEBUG
# Server configuration
server:
  port: 8082
# Security configuration
security:
  user:
    name: user
    password: user