# Spring Boot configuration
spring:
  profiles:
    active: development
# Database
  data:
    mongodb:
      uri: ${URI_MONGODB}

# Logging
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    com.hello: DEBUG
    org.springframework: INFO
    org.mongodb: DEBUG
# Server configuration
server:
  port: ${SERVER_PORT}

# Security configuration
#security:
#  user:
#    name: user
#    password: user